### ISSUE TITLE
Make more types Send+Sync

### ISSUE THREAD

**Issue by timokoesters** [Kerollmops/heed#112]
For my program I need Send+Sync on more types because they are used in an async context. Here's an example error for iterators:
> `*mut lmdb_sys::MDB_cursor` cannot be sent between threads safely`

It would also be nice if heed::Error was Send+Sync.

Is that possible or do you not support this?

**Comment by Kerollmops** [comment]
You can move to the v0.10.6 version of this crate where the Error type is `Send` + `Sync` but you'll lose the De/Serialization error info.

However, I didn't implement `Send` for the cursor type as I thought it is unsafe and invalid according to the documentation, as moving a transaction is also invalid.
