### ISSUE TITLE
Find a real name for this library

### ISSUE THREAD

**Issue by Kerollmops** [Kerollmops/heed#14]
I thought about a shorter name for this library, just remember that it is a typed key-value store based on LMDB which itself means Lightning Memory-Mapped Database.
So here is a list of names I thought of:

  - zlmdb
  - whirlwind
  - discern
  - heed
  - agile
  - deft

**Comment by jonsecchis** [comment]
I'm fond of absolute minimalism, so as an alternative, one name that comes to my mind is…

> **LMKV**, the *Lightning Memory-Mapped Key Value store for Rust*

It sounds like LMDB and it has the same length. *KV* is also a very relevant term in the industry. Plus there are nice domain extensions available for it, such as `.io`. If this is something you like, I would gladly donate it to the project and maintain it for at least 2 years. I think the project could really use a website. As a professional designer, I can also provide a logotype and any collateral artifacts that might be needed.

As another way to contribute to the project, I may be able to delegate copywriting and reviewing tasks to my talented colleagues at Apex, which is the startup where we use this library.

Please don't feel any pressure to vouch for my suggestions, I would contribute in the same way regardless of the name you pick.

I'm feeling we can put some traction on this enterprise :)
