### ISSUE TITLE
Is it possible to specify LMDB flags such as MDB_NOSYNC?

### ISSUE THREAD

**Issue by lquerel** [Kerollmops/heed#15]
Looks like flags are not yet supported. Did I miss them?

Thanks for this nice wrapper.

Laurent

**Comment by Kerollmops** [comment]
Hi,

Heed do not support the `MDB_NOSYNC` flag for the moment in part because:
  1. I didn't needed it for my search engine
  2. The documentation is explicit on the fact that this flag is dangerous:
      > `MDB_NOSYNC` Don't flush system buffers to disk when committing a transaction. This optimization means a system crash can corrupt the database or lose the last transactions if buffers are not yet flushed to disk. The risk is governed by how often the system flushes dirty buffers to disk and how often `mdb_env_sync()` is called. However, if the filesystem preserves write order and the `MDB_WRITEMAP` flag is not used, transactions exhibit `ACI` (atomicity, consistency, isolation) properties and only lose D (durability). I.e. database integrity is maintained, but a system crash may undo the final transactions. Note that (`MDB_NOSYNC | MDB_WRITEMAP`) leaves the system with no hint for when to write transactions to disk, unless `mdb_env_sync()` is called. (`MDB_MAPASYNC | MDB_WRITEMAP`) may be preferable. This flag may be changed at any time using `mdb_env_set_flags()`.

I am still open to pull request and will probably accept one that allow to specify this flag under an `unsafe fn no_sync()` and a `fn flush()` functions together.

**Comment by lquerel** [comment]
Yes this kind of flag is not without risk. However in some contexts there are very useful. I need for example to build a big read only database of several billions of entries. I need to be able to rebuild it on demand and using `MDB_NOSYNC` (+ some other flags) can speed the insertion process by a lot. 
I’ll send a PR this weekend. Will you accept something like an enum containing all the flags supported by LMDB + a function `flags` to set a collection of flags in your builder?

**Comment by Kerollmops** [comment]
Yeah absolutely, I will probably merge it if it is marked `unsafe` however :)
