### ISSUE TITLE
Trait std::iter::DoubleEndedIterator

### ISSUE THREAD

**Issue by placrosse** [Kerollmops/heed#30]
Since a LMDB cursor is capable of quickly going to last, and getting the previous entry, it should support the DoubleEndedIterator, allowing last to first iteration of a range.

**Comment by Kerollmops** [comment]
Yes, I thought about this but did not implement it because I did not needed it.

However, there is a little issue relative to the [`DoubleEndedIterator`](https://doc.rust-lang.org/stable/std/iter/trait.DoubleEndedIterator.html) expected behavior:
> It is important to note that both back and forth work on the same range, and do not cross: iteration is over when they meet in the middle.

This is not how an [LMDB cursor](http://www.lmdb.tech/doc/group__mdb.html#ga1206b2af8b95e7f6b0ef6b28708c9127) work, the cursor itself moves forward and backward but the expected behavior of `DoubleEndedIterator` is that there should be **two** cursors, one that moves forward from the start of the range, one that moves backward from the end and when they meet, the iteration must stop.

It is possible to implement a special `DoubleEndedCursor` type that is composed of **two** cursors, that can consume from the end, from the back and that stops when both meets in the middle. Notice that we need to keep both cursors keys in memory to be able to detect when we reach the other cursor's position (that can be only the memory mapped raw bytes).

I will not work on this for the moment, but I am happy to guide you if you want to 😃

**Comment by placrosse** [comment]
I saw that issue about the double cursor.  What I really need is to be able to select the last valid key from a range, without iterating through everything.  I didn't see how it was possible in the current API.

The suggestion for DoubleEndedIterator came about while reviewing https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.rev.

What do you think would be the most idiomatic way to use heed to determine the last existing key in a db key range?  I'm willing to implement.

**Comment by Kerollmops** [comment]
I think that using a combination of [`mdb_cursor_get`](http://www.lmdb.tech/doc/group__mdb.html#ga48df35fb102536b32dfbb801a47b4cb0) with [`MDB_SET_RANGE`](www.lmdb.tech/doc/group__mdb.html#ga1206b2af8b95e7f6b0ef6b28708c9127). Adding a method `last` to the [`RoRange` type](https://github.com/Kerollmops/heed/blob/b65740775bbbe8c55bc0beb7c028023b2a8f1554/src/db/mod.rs#L99-L104) like for the [RwRange](https://github.com/Kerollmops/heed/blob/b65740775bbbe8c55bc0beb7c028023b2a8f1554/src/db/mod.rs#L156-L170) would be great. The `RoRange::last` method should take self by value (not ref) as it can no longer make progress and must call [`RoCursor::move_on_key_greater_than_or_equal_to`](https://github.com/Kerollmops/heed/blob/b65740775bbbe8c55bc0beb7c028023b2a8f1554/src/cursor.rs#L76-L102).

**Comment by placrosse** [comment]
Clément, after reviewing again the trait https://doc.rust-lang.org/nightly/std/iter/trait.DoubleEndedIterator.html, I see we only need to implement a single method properly: `fn next_back(&mut self) -> Option<Self::Item>`

I'm thinking this may not be very difficult.  How do you feel about an approach that uses the existing, single cursor, but adds a few variables to keep track of the current key position from the far end?  If they aren't used on a particular cursor/range, we could code it such that a quick boolean check is the only extra overhead.  If it has been used, we can set a bool indicating the last position used (forward or reverse), and if the current call is the same direction, then we just proceed with using the underlying LMDB cursor with a `next` or `prev` motion, as appropriate.  If the prior call was the opposite direction of the current, we first need to have the LMDB cursor set its current position back to the last found key from that direction, prior to moving to the next key.

What is your opinion of this?

**Comment by Kerollmops** [comment]
Keeping only one LMDB cursor to simulate two cursors is not the best solution in thing. The boolean overhead you talk about is hand in hand with the value of the last key visited, each time the user will call `next` follow by `next_back` (or the reverse) we need to ask LMDB to seek to the previous visited key, this is `O(log n)`.

I though that what you wanted was to find the last key of a range, in other word, the key just aqual or lower than the last key of a range.
> What do you think would be the most idiomatic way to use heed to determine the last existing key in a db key range?

I would prefer to create an [`RoRange::last`](https://github.com/Kerollmops/heed/blob/86262ffae25ef664e7ec5501f28995f52d7149bf/src/db/mod.rs#L99-L104) method. Based on the [`RoRange.end_bound`](https://github.com/Kerollmops/heed/blob/86262ffae25ef664e7ec5501f28995f52d7149bf/src/db/mod.rs#L100) value:
  - if the value is [`Bound::Included`](https://doc.rust-lang.org/std/ops/enum.Bound.html), get the end bound key and call [`mdb_cursor_get`](http://www.lmdb.tech/doc/group__mdb.html#ga48df35fb102536b32dfbb801a47b4cb0) with [`MDB_SET_KEY`](http://www.lmdb.tech/doc/group__mdb.html#ga1206b2af8b95e7f6b0ef6b28708c9127):
    - if an entry is found, return it, that's the last key of the range.
    - if no key is found, then call `mdb_cursor_get` with `MDB_PREV`, and check that the key found is _not before_ [the first key of the range](https://github.com/Kerollmops/heed/blob/86262ffae25ef664e7ec5501f28995f52d7149bf/src/db/mod.rs#L101).
  - if the value is `Bound::Excluded`, get the bound key and call `mdb_cursor_get`:
    - if an entry is found, call `mdb_cursor_get` with `MDB_PREV`, and check that the key found is _not before_ the first key of the range.
    - if no entry is found, do the same as above, call `MDB_PREV` and check if it exists in the range.
  - if the value is `Bound::Unbounded`, just call `mdb_cursor_get` with `MDB_LAST`, the last key of the database.

You can see how I call LMDB functions [in the cursor.rs file](https://github.com/Kerollmops/heed/blob/86262ffae25ef664e7ec5501f28995f52d7149bf/src/cursor.rs#L27-L48), for example.

**Comment by placrosse** [comment]
While finding the last key does work for a good amount of use cases, it leaves us still with an ugly solution for retrieving the last ”x” items.  I don’t see an elegant means to accomplish, for example, retrieval of the last 10 values that are within the range.

**Comment by Kerollmops** [comment]
A first good enough solution that doesn't involve any overhead would be to introduce a `rev_range` method that return a `RevRange` iterator.

In a second step we could introduce a `DoubleEndedRange` that combines both iterators.

**Comment by myfreeweb** [comment]
Wouldn't it be possible to satisfy the "meet in the middle" requirement by counting?

i.e. `next` does `self.nexts += 1`, `next_back` does `self.next_backs += 1`, and both early-return `None` if `self.nexts + self.next_backs == self.len` (where `self.len` is a cached value of the database's `.len()`)

**Comment by Kerollmops** [comment]
@myfreeweb The problem is that `self.len` doesn’t exist as the cursor is not aware of the exact number of entries lying between the bounds. Computing the length of the cursors (the number of entries between the bounds) is `O(log n)`, this can be a big overhead.

> Also the second cursor could be created lazily on the first double-ended operation

Yeah, that is a good idea!
