### ISSUE TITLE
Moving from zerocopy to bytemuck

### ISSUE THREAD

**Issue by Kerollmops** [Kerollmops/heed#82]
This library currently uses [the zerocopy crate](https://lib.rs/zerocopy) to provide some useful codecs for common types and types which implements the [`AsBytes`](https://docs.rs/zerocopy/0.3.0/zerocopy/trait.AsBytes.html)/[`FromBytes`](https://docs.rs/zerocopy/0.3.0/zerocopy/trait.FromBytes.html) traits (i.e. `u8`, `[u8]`). I find it complex/impossible to contribute to this crate as there is no repository for this crate only as it has been developed for the new fuchsia OS; sources of this crate are mixed with the source of the OS (in a sub-repository at least).

[The bytemuck library](https://lib.rs/bytemuck) seems to be much easier to contribute to; it is hosted on Github, seems to be much more popular than the former (114k downloads by month compared to 15k). It brings a better API, at least for heed, as it can return [information on which kind of problem happens when a cast fails](https://docs.rs/bytemuck/1.4.1/bytemuck/enum.PodCastError.html), it would [simplify some codecs](https://github.com/Kerollmops/heed/blob/3f170c80b6e39af183bcf481d5afeefeec87cf6e/heed-types/src/cow_slice.rs#L42-L68).

I looked into the crate and found that the change, despite breaking, will be easy. I also found out that we can cast slices of different types by using [the `try_cast_slice` function](https://docs.rs/bytemuck/1.4.1/bytemuck/fn.try_cast_slice.html).

I am just not sure how to expose integers as big-endian, ensuring that the global order is preserved. We will maybe need to create codecs [for every integer type like what zerocopy has done](https://docs.rs/zerocopy/0.3.0/zerocopy/byteorder/index.html) using [byteorder maybe](https://lib.rs/byteorder).

**Comment by joshlf** [comment]
Hi @Kerollmops , just wanted to let you know that [zerocopy is on GitHub now](https://github.com/google/zerocopy) in case there are still zerocopy features that would be useful to you (like byteorder-aware types). If not, of course disregard this message 🙂

**Comment by Kerollmops** [comment]
Thank you very much @joshlf,

Is there a page that compares both crates feature-wise? The only issue that I found is [this one on bytemuck](https://github.com/Lokathor/bytemuck/issues/13). I'll evaluate both crates.

Note that [I will release a new version of heed](https://github.com/meilisearch/heed/pull/128) with a lot of things rewritten and this choice between heed and bytemuck will be the last choice.

**Comment by joshlf** [comment]
> Is there a page that compares both crates feature-wise? The only issue that I found is [this one on bytemuck](https://github.com/Lokathor/bytemuck/issues/13). I'll evaluate both crates.

At this point, we've both adopted features from each other, so it really depends on your specific use cases. If you can describe specific use cases, I can try to speak to what the two crates provide for those use cases (with the obvious bias that I know zerocopy a lot better than I know bytemuck), but I don't maintain a comparison page. For the current state of zerocopy, I'd check out our [latest alpha release](https://docs.rs/zerocopy/0.7.0-alpha.1/zerocopy/index.html). For the future state, I'd check out our [Q4 2022 roadmap](https://github.com/google/zerocopy/issues/98) (that roadmap is best effort, so definitely don't make any decisions that rely on that roadmap coming to fruition on schedule).

I'd also love to hear any feedback you have or feature requests! Even just "I want to do <vague, high-level description> and I'm not sure how" is very helpful.

**Comment by Kerollmops** [comment]
Hey @joshlf,

I'm sorry for not getting back to you sooner. I just released a new version of heed v0.20.0-alpha.0 to let people test the version of the `BytesEncode`/`BytesDecode` traits backed by _bytemuck_. However, as we will also test it at Meilisearch inside milli, we will be able to ensure that it is correct and works great. If we find issues, we can roll back and use zerocopy or ask you for some advice.
