### ISSUE TITLE
Support env_stat

### ISSUE THREAD

**Issue by Keats** [Kerollmops/heed#97]
Taken from the python bindings docs for LMDB: https://lmdb.readthedocs.io/en/release/#lmdb.Environment.stat

Would it be possible to expose that function?

**Comment by Kerollmops** [comment]
Hey @Keats,

I believe it is easy to add two new methods:
  - The `Env::stat` method that just calls [`mdb_env_stat`](https://docs.rs/lmdb-rkv-sys/0.9.5/lmdb_sys/fn.mdb_env_stat.html) with the env pointer.
  - The `Database::stat` method that calls the [`mdb_env_stat`](https://docs.rs/lmdb-rkv-sys/0.9.5/lmdb_sys/fn.mdb_stat.html) with the database integer.

However, I would prefer that we return two different structs for the two methods, I don't find the `Mdb_val` struct clear enough, what do you think. And two kill two birds with one stone, we could fix #56 by using these stats.

**Comment by Keats** [comment]
>  I don't find the Mdb_val struct clear enough

What would you change?

The main thing I wanted the DB stat struct for is the number of entries to (so it's not slow like right now, solving #56 as you point out) and to calculate the space used (https://wiki.samba.org/index.php/Using_the_lmdb_database_backend#Calculating_space_used). I don't think I would need the env stat struct myself but it could definitely be added for the sake of completeness.

**Comment by Kerollmops** [comment]
> What would you change?

First thing I don't quite like is the documentation and those other fields that are not **that** obvious.

> I don't think I would need the env stat struct myself but it could definitely be added for the sake of completeness.

Maybe you could first fix #56 by extracting the number of entries from the `Mdb_stat` struct, this way you don't expose it, then we will introduce the new methods which return two new structs with explicit fields and maybe one that contains the _space used_?

**Comment by Keats** [comment]
PR for #56: https://github.com/Kerollmops/heed/pull/99

The rest is not that important to me so if you're doing a lot of changes, I'll do another PR with the db stat structs later once you're done (unless you beat me to it).

**Comment by Kerollmops** [comment]
Closed by #100.
